version: '3'

services:

    import:
        container_name: python3
        build:
            context: .
            dockerfile: ./python/Dockerfile
        stdin_open: true
        tty: true
        volumes:
            - .:/home/python